### ISSUE TITLE
use SpiDriver to create a EthDriver

### ISSUE THREAD

**Issue by teamplayer3** [esp-rs/esp-idf-svc#174] opened 2022-11-24 08:25 UTC
As discussed in #173, the `EthDriver` in this crate can be based on a`SpiDriver` of [esp-idf-hal](https://github.com/esp-rs/esp-idf-hal).

To investigate this further, it must be tested if the `EthDriver` works if another spi device is connected on the bus, which shares the `SpiDriver`. This would be possible with the new design.

**Comment by ivmarkov** [comment] 2023-03-26 14:25
Dupe of #223, closing.

**Closed by ivmarkov** 2023-03-26 14:25 UTC
